name: Deploy React App to Vercel

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug:List files
        run: ls -R

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 5. Deploy to Vercel (Production or Staging based on branch)
      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        run: npx vercel --prod \
          --cwd=. \
          --token=${{ secrets.WfSYUi30dHt5vJ5GB0XKUVg7 }} \
          --scope=${{ secrets.team_8kXRHgQOIxU0PUWLPWDoW4Rw }} \
          --project=${{ secrets.prj_Rhdn03DuBNyGFiP2UOxtQRipDBGd }} \
          --confirm

      - name: Deploy to Vercel (Staging)
        if: github.ref == 'refs/heads/develop'
        run: npx vercel \
          --cwd=. \
          --token=${{ secrets.WfSYUi30dHt5vJ5GB0XKUVg7 }} \
          --scope=${{ secrets.team_8kXRHgQOIxU0PUWLPWDoW4Rw }} \
          --project=${{ secrets.prj_Rhdn03DuBNyGFiP2UOxtQRipDBGd }} \
          --confirm
